#!/bin/bash








for ((n=1;$n<=100;n++)); do
   $((X++)) 
	if [[ "$X" -gt 5 ]]; then 
		X=1
		c=$(( 36 - "$X" )) 

	fi
	printf '\0$c["$c"%s\n' "$X"
done






# 
# <Down>
# 
# ANSI codes
# 
# Black            \e[0;30m
# Blue             \e[0;34m
# Green            \e[0;32m
# Cyan             \e[0;36m
# Red              \e[0;31m
# Purple           \e[0;35m
# Brown            \e[0;33m
# Gray             \e[0;37m
# Dark Gray        \e[1;30m
# Light Blue       \e[1;34m
# Light Green      \e[1;32m
# Light Cyan       \e[1;36m
# Light Red        \e[1;31m
# Light Purple     \e[1;35m
# Yellow           \e[1;33m
# White            \e[1;37m
# 
# moves() {                                                                    
#     u="\033[${c}A" #moves cursor up # lines                                  
#     d="\033[${c}B" #moves cursor down # lines                                
#     r="\033[${c}C" #moves cursor right # columns                             
#     l="\033[${c}D" #moves cursor left # columns                              
#     n="\033[${c}E" #moves cursor to beginning of next line, # lines down     
#     p="\033[${c}F" #moves cursor to beginning of previous line, # lines up   
# }                                                                            
#                                                                              
# print() {                                                                    
#     local color format text                                                  
#     if [[ "$1" ~= ([[:alpha:]])([[:alpha]]) ]]; then                         
#         color="${!BASE_MATCH[1]}"; format="${!BASE_MATCH[2]}"                
#         code="\033[${!BASE_MATCH[1]},${!BASE_MATCH[2]}m"                     
#     else                                                                     
#         code="\033[${!BASE_MATCH[1]}"                                        
#     fi                                                                       
#     R='\033[0m'    #reset                                                    
#     B='\033[1m'    #bold                                                     
#     D='\033[2m'    #dim                                                      
#     I='\033[8m'    #invisible                                                
#     L='\033[5m'    #blinking  
# 
# 
# 
# 
# 
# 
# gg
